package spec

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// MonacoFile is generated alongside the reference and checked by dsl:check.
const MonacoFile = "studio/src/lib/iterDsl.generated.ts"

// Monaco renders the editor's lexical and property vocabulary. The caller
// supplies parser.Keywords(): spec stays a leaf, since the parser itself
// imports this registry to diagnose property names.
func Monaco(lexicalKeywords []string) string {
	keywords := append([]string{}, lexicalKeywords...)
	sort.Strings(keywords)
	declarations := []string{}
	properties := make(map[string][]string, len(Kinds))
	for _, kind := range Kinds {
		if kind.Role == Declaration || kind.Role == Node {
			declarations = append(declarations, kind.Name)
		}
		properties[kind.Name] = append([]string{}, kind.Names()...)
		sort.Strings(properties[kind.Name])
	}
	sort.Strings(declarations)
	var b strings.Builder
	b.WriteString("// Generated by `iterion dsl spec --write` from parser.Keywords() and pkg/dsl/spec.\n// Do not edit by hand; task dsl:check verifies this module.\n\n")
	for _, item := range []struct {
		name  string
		value any
	}{
		{"iterDslKeywords", keywords},
		{"iterDslDeclarations", declarations},
		{"iterDslPropertiesByKind", properties},
	} {
		// These values contain only strings/slices/maps, so encoding cannot fail.
		raw, _ := json.MarshalIndent(item.value, "", "  ")
		fmt.Fprintf(&b, "export const %s = %s as const;\n\n", item.name, raw)
	}
	b.WriteString("export const iterDslProperties = [...new Set(Object.values(iterDslPropertiesByKind).flat())];\n")
	return b.String()
}
