// Package permissionhook adapts third-party CLI PreToolUse payloads to
// iterion's shared permission.Policy evaluator.
package permissionhook

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/SocialGouv/iterion/pkg/backend/permission"
)

const (
	BackendGrok = "grok"
	BackendKimi = "kimi"
)

type event struct {
	ToolName      string         `json:"tool_name"`
	ToolInput     map[string]any `json:"tool_input"`
	GrokToolName  string         `json:"toolName"`
	GrokToolInput map[string]any `json:"toolInput"`
}

// Run reads one native hook event, evaluates it, and writes the backend's
// exact blocking dialect. Malformed input and unreadable policy state fail
// closed by emitting a deny verdict; returning an error alone would make both
// CLIs fail open.
func Run(backend, policyPath string, in io.Reader, out io.Writer) error {
	if backend != BackendGrok && backend != BackendKimi {
		return fmt.Errorf("permission hook: unsupported backend %q", backend)
	}

	policy, err := readPolicy(policyPath)
	if err != nil {
		return writeDeny(backend, out, "iterion could not load the permission policy; the tool call was blocked")
	}
	raw, err := io.ReadAll(io.LimitReader(in, 4<<20))
	if err != nil {
		return writeDeny(backend, out, "iterion could not read the permission request; the tool call was blocked")
	}
	var ev event
	if err := json.Unmarshal(raw, &ev); err != nil {
		return writeDeny(backend, out, "iterion could not decode the permission request; the tool call was blocked")
	}
	toolName, toolInput := ev.ToolName, ev.ToolInput
	if backend == BackendGrok {
		toolName, toolInput = ev.GrokToolName, ev.GrokToolInput
	}
	if strings.TrimSpace(toolName) == "" {
		return writeDeny(backend, out, "iterion received a permission request without a tool name; the tool call was blocked")
	}
	if toolInput == nil {
		toolInput = map[string]any{}
	}

	decision, rule := policy.Evaluate(toolName, toolInput)
	switch decision {
	case permission.Allow:
		return nil
	case permission.Ask:
		return writeDeny(backend, out, fmt.Sprintf("%s needs operator approval, which %s cannot pause for; the tool call was blocked", toolName, backend))
	default:
		return writeDeny(backend, out, permission.DenyMessage(toolName, toolInput, rule))
	}
}

func readPolicy(path string) (*permission.Policy, error) {
	// #nosec G304 -- path is generated by the parent iterion process and
	// passed directly to its hidden hook subprocess.
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg permission.PolicyConfig
	if err := json.Unmarshal(raw, &cfg); err != nil {
		return nil, err
	}
	return permission.NewPolicyFromConfig(cfg)
}

func writeDeny(backend string, out io.Writer, reason string) error {
	enc := json.NewEncoder(out)
	switch backend {
	case BackendGrok:
		return enc.Encode(map[string]any{
			"decision": "deny",
			"reason":   reason,
		})
	case BackendKimi:
		return enc.Encode(map[string]any{
			"hookSpecificOutput": map[string]any{
				"permissionDecision":       "deny",
				"permissionDecisionReason": reason,
			},
		})
	default:
		return fmt.Errorf("permission hook: unsupported backend %q", backend)
	}
}
