package botimport

import (
	"fmt"
	"strings"
)

// ReportEntry is one import event, anchored to the original JS line.
type ReportEntry struct {
	Line int    // 1-based line in the source .js (0 = whole file)
	Text string // human sentence, one line
}

// Report is the truthful record of a lossy import: what mapped
// cleanly, what degraded into a placeholder or promoted var ("hole"),
// and what was dropped outright. It is embedded verbatim at the top of
// the generated .bot so the draft can never masquerade as a faithful
// translation.
type Report struct {
	SourceFile string
	// Mapped: constructs translated to real DSL.
	Mapped []ReportEntry
	// Placeholders: constructs kept as annotated `## IMPORT` comments.
	Placeholders []ReportEntry
	// Holes: JS expressions promoted to vars the operator must fill.
	Holes []ReportEntry
	// Dropped: constructs with no .bot equivalent, removed (visibly).
	Dropped []ReportEntry
}

func (r *Report) mapped(line int, format string, args ...any) {
	r.Mapped = append(r.Mapped, ReportEntry{Line: line, Text: fmt.Sprintf(format, args...)})
}

func (r *Report) placeholder(line int, format string, args ...any) {
	r.Placeholders = append(r.Placeholders, ReportEntry{Line: line, Text: fmt.Sprintf(format, args...)})
}

func (r *Report) hole(line int, format string, args ...any) {
	r.Holes = append(r.Holes, ReportEntry{Line: line, Text: fmt.Sprintf(format, args...)})
}

func (r *Report) dropped(line int, format string, args ...any) {
	r.Dropped = append(r.Dropped, ReportEntry{Line: line, Text: fmt.Sprintf(format, args...)})
}

// NeedsAttention is true when the draft contains anything an operator
// must resolve before the bot is trustworthy.
func (r *Report) NeedsAttention() bool {
	return len(r.Placeholders) > 0 || len(r.Holes) > 0 || len(r.Dropped) > 0
}

// FormatEntries renders report entries as "js:<line> <text>" strings —
// the wire/CLI presentation shared by `iterion import --json` and the
// studio import route.
func FormatEntries(entries []ReportEntry) []string {
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.Line > 0 {
			out = append(out, fmt.Sprintf("js:%d %s", e.Line, e.Text))
		} else {
			out = append(out, e.Text)
		}
	}
	return out
}

// header renders the `## IMPORT REPORT` comment block for the top of
// the generated .bot.
func (r *Report) header() string {
	var b strings.Builder
	b.WriteString("## IMPORT REPORT — generated by `iterion import` from " + r.SourceFile + "\n")
	b.WriteString("## This is a LOSSY draft: review every IMPORT marker before running it.\n")
	section := func(title string, entries []ReportEntry) {
		if len(entries) == 0 {
			return
		}
		b.WriteString("##\n## " + title + ":\n")
		for _, e := range entries {
			if e.Line > 0 {
				fmt.Fprintf(&b, "##   - js:%d %s\n", e.Line, e.Text)
			} else {
				fmt.Fprintf(&b, "##   - %s\n", e.Text)
			}
		}
	}
	section("Mapped", r.Mapped)
	section("Holes (vars to fill)", r.Holes)
	section("Placeholders (unmapped constructs)", r.Placeholders)
	section("Dropped", r.Dropped)
	if !r.NeedsAttention() {
		b.WriteString("##\n## Clean import: no placeholders, holes, or drops.\n")
	}
	return b.String()
}
