package botimport

import (
	"strings"
	"testing"

	"github.com/SocialGouv/iterion/pkg/dsl/ir"
)

// C018 ("no model/backend and no auto-detectable credential") is an environment
// verdict, not a lowering defect: an imported draft deliberately leaves
// model/backend unset so a run auto-detects the host credential. On a machine
// WITH a credential the compiler never emits it, so the golden tests pass; in a
// credential-less environment (CI, a fresh checkout) it fired and turned every
// import into "generated draft does not compile".
//
// The triage is tested on synthetic diagnostics so the assertion holds
// regardless of whether the machine running the test has a credential.
func TestDraftCompileErrors_SkipsMissingModelOrBackend(t *testing.T) {
	rep := &Report{}
	errs := draftCompileErrors([]ir.Diagnostic{{
		Code:     ir.DiagMissingModelOrBackend,
		Severity: ir.SeverityError,
		Message:  `agent "surveyor" must set 'model' or 'backend'`,
		NodeID:   "surveyor",
	}}, rep)

	if len(errs) != 0 {
		t.Fatalf("C018 must not fail the import, got %v", errs)
	}
	// Skipped SILENTLY: the Report is embedded verbatim in the generated .bot,
	// so recording an env-dependent diagnostic would make the generated bytes
	// (and the goldens) differ between a machine with a credential and one
	// without — the very non-determinism this fix removes.
	if len(rep.Placeholders) != 0 || rep.NeedsAttention() {
		t.Fatalf("C018 must not enter the embedded report: %+v", rep)
	}
}

func TestDraftCompileErrors_KeepsRealErrorsAndFoldsWarnings(t *testing.T) {
	rep := &Report{}
	errs := draftCompileErrors([]ir.Diagnostic{
		{Code: ir.DiagMissingModelOrBackend, Severity: ir.SeverityError, Message: "env verdict"},
		{Code: ir.DiagDuplicateNodeID, Severity: ir.SeverityError, Message: `duplicate node "a"`},
		{Code: ir.DiagCodexDiscouraged, Severity: ir.SeverityWarning, Message: "codex discouraged"},
	}, rep)

	if len(errs) != 1 || !strings.Contains(errs[0], `duplicate node "a"`) {
		t.Fatalf("a genuine lowering error must still fail the import, got %v", errs)
	}
	if len(rep.Placeholders) != 1 || !strings.Contains(rep.Placeholders[0].Text, "codex discouraged") {
		t.Fatalf("warnings must stay visible in the report, got %+v", rep.Placeholders)
	}
}
