package botimport

import (
	"fmt"
	"strings"

	"github.com/SocialGouv/iterion/pkg/dsl/ir"
	"github.com/SocialGouv/iterion/pkg/dsl/parser"
)

// validateDraft compiles the generated source before anyone can write
// it to disk (same contract as botscaffold): an import that emits an
// uncompilable draft is a bug in the lowering, surfaced loudly — never
// shipped as a "draft the operator will fix". Non-error diagnostics
// are folded into the report so warnings stay visible.
func validateDraft(srcFile, botSrc string, rep *Report) error {
	pr := parser.Parse(srcFile+".bot", botSrc)
	var errs []string
	for _, d := range pr.Diagnostics {
		if d.Severity == parser.SeverityError {
			errs = append(errs, d.Error())
		}
	}
	if pr.File == nil || len(errs) > 0 {
		return fmt.Errorf("internal: generated draft does not parse (import bug, not an input problem):\n%s", strings.Join(errs, "\n"))
	}
	cr := ir.Compile(pr.File)
	errs = append(errs, draftCompileErrors(cr.Diagnostics, rep)...)
	if cr.Workflow == nil || len(errs) > 0 {
		return fmt.Errorf("internal: generated draft does not compile (import bug, not an input problem):\n%s", strings.Join(errs, "\n"))
	}
	return nil
}

// draftCompileErrors triages the draft's compile diagnostics: warnings are
// folded into the report, errors are returned — except C018, which is skipped.
//
// C018 (no model/backend and no auto-detectable credential) is an ENVIRONMENT
// verdict, not a lowering defect — the same call botscaffold makes for its
// zero-config template. The imported draft deliberately leaves model/backend
// unset so a run auto-detects the host's credential, so a credential-less
// environment (CI, a fresh machine) must not turn a structurally sound draft
// into an import failure. It is skipped SILENTLY rather than reported: the
// Report is embedded verbatim in the generated .bot, so recording an
// env-dependent diagnostic would make the generated bytes — and the goldens —
// differ between a machine with a credential and one without. The missing
// credential is surfaced later, at run/validate time.
func draftCompileErrors(diags []ir.Diagnostic, rep *Report) []string {
	var errs []string
	for _, d := range diags {
		if d.Severity != ir.SeverityError {
			rep.placeholder(0, "compile warning on the draft: %s", d.Error())
			continue
		}
		if d.Code == ir.DiagMissingModelOrBackend {
			continue
		}
		errs = append(errs, d.Error())
	}
	return errs
}
