package bots

import (
	"os"
	"strings"
	"testing"
)

// A host wake deliberately clears operator_message in normalize_chat_turn.
// Terra therefore receives the host-attested event, never the launch's stale
// message, and may send that evidence through private reflection if needed.
func TestCopilotHostEventDoesNotReviveInitialMessage(t *testing.T) {
	raw, err := os.ReadFile("copilot/main.bot")
	if err != nil {
		t.Fatalf("read copilot: %v", err)
	}
	src := string(raw)
	system := copilotContractSection(t, src, "prompt copi_system:", "prompt copi_user:")

	const precedence = `operator_message: "if(input.host_event, '', input.operator_message)"`
	if !strings.Contains(src, precedence) {
		t.Fatalf("Copi normalization must keep operator_message empty for a host event; want %q", precedence)
	}
	if !strings.Contains(src, `host_event:           "{{outputs.normalize_chat_turn.host_event}}"`) {
		t.Fatal("Copi Terra no longer receives the host event after chat normalization")
	}
	if strings.Contains(src, `operator_message: "if(input.operator_message, input.operator_message, input.initial_message)"`) {
		t.Fatal("Copi still revives initial_message on a host-event turn")
	}
	requireCopilotContract(t, "Copi watched-run recovery", system,
		"Recovery evidence discipline",
		"A descendant fail/cancellation alone does not prove a source defect.",
		"the smallest recovery is one run.resume on the awaited root.",
		"If unchanged resume immediately reproduces the failure, do not repeat.",
		"an existing version or lock pin does not prove repair.",
		"Require a distinct post-diagnosis source repair confirmed by action-completed and linked read evidence before run recovery.",
	)
}

func TestCopilotFailedResumableRecoveryOrder(t *testing.T) {
	raw, err := os.ReadFile("copilot/skills/iterion-run-debug.md")
	if err != nil {
		t.Fatalf("read Copi run-debug playbook: %v", err)
	}
	src := string(raw)
	requireCopilotContract(t, "Copi failed-resumable recovery", src,
		"For a `failed_resumable` root, start with the smallest recovery.",
		"A descendant reaching `fail`, exhausting a correction loop, or being cancelled",
		"propose exactly one `run.resume` for the root",
		"Do not propose a rewind merely to make a failed descendant look fresh.",
		"If that unchanged resume reaches the same failure immediately, do not repeat it",
	)
}

// A watch episode once arrived after Copi had published a verified companion-
// file repair but before Studio saved it. The watch reply emitted an empty
// file_changes array, which intentionally retires the newest Studio offer, and
// then surfaced a gate generated by the known-uncorrected source. Keep the
// behavioral closure explicit wherever watched-run recovery is taught.
func TestCopilotWatchWakePreservesPendingAuthoringRepair(t *testing.T) {
	mainRaw, err := os.ReadFile("copilot/main.bot")
	if err != nil {
		t.Fatalf("read Copi main bot: %v", err)
	}
	debugRaw, err := os.ReadFile("copilot/skills/iterion-run-debug.md")
	if err != nil {
		t.Fatalf("read Copi run-debug playbook: %v", err)
	}
	main := string(mainRaw)
	system := copilotContractSection(t, main, "prompt copi_system:", "prompt copi_user:")
	debug := string(debugRaw)

	requireCopilotContract(t, "Copi pending repair", system,
		"A previously proposed repair stays pending until a matching receipt plus read evidence",
		"A watch event is evidence, not a receipt.",
		"re-emit the complete verified proposal at most once for that distinct event",
		"if its binding and before anchors remain current",
		"A gate produced by known-uncorrected source and conflicting with the pending objective is not actionable",
	)
	requireCopilotContract(t, "Copi run-debug repair handoff", debug,
		"The system kernel owns authoring authority, proposal shape, validation, receipts, and pending-effect rules",
		"After a confirmed source repair, re-read the affected source and target run.",
	)
}
