// Pipeline board — read-model client for the single, global, runtime-derived
// board. Distinct from api/native.ts: /board remains the editable backlog,
// while this API projects every root pipeline (and not-yet-launched native
// task) into five fixed, non-draggable lanes. Card position is derived from
// server state only — moves are explicit button-driven ready-state writes.

import { apiRequest } from "./client";
import type { NativeIssue } from "./native";

const BASE = "/api/v1/pipeline-board";

// The five fixed lanes, in the order the server emits them.
export interface PipelineBoardColumn {
  id: string; // "opened" | "in_progress" | "closed"
  title: string;
  kind: string;
}

// One paused human interaction somewhere in a root's tree (the root itself or
// any descendant). The IN_PROGRESS card presents these one at a time; each
// answer targets the exact run_id shown here.
export interface PipelineBoardPendingReview {
  run_id: string;
  workflow_name?: string;
  bot_id?: string;
  node_id?: string;
  interaction_id?: string;
  questions?: Record<string, unknown>;
  /** When this exact pending turn joined the FIFO review queue. */
  updated_at: string;
  // Rendered `instructions:` markdown of the paused human node.
  instructions?: string;
  /** Concise operator instructions generated by the AI reviewer. */
  review_brief?: PipelineBoardReviewBrief;
  /** Validated artifact-file references attached to this exact review turn. */
  media?: PipelineBoardReviewMedia[];
  /** Guided `interaction: review` dialogue and reserved-action configuration. */
  review?: PipelineBoardReviewGate;
  depth: number;
}

export type PipelineBoardReviewBriefPoints =
  | [string]
  | [string, string]
  | [string, string, string];

export interface PipelineBoardReviewBrief {
  version: 1;
  source: "ai";
  points: PipelineBoardReviewBriefPoints;
}

export type PipelineBoardReviewMediaKind =
  | "image"
  | "audio"
  | "video"
  | "doc"
  | "data";

export interface PipelineBoardReviewMedia {
  run_id?: string;
  path: string;
  kind: PipelineBoardReviewMediaKind;
  mime?: string;
  size?: number;
  caption?: string;
}

export interface PipelineBoardReviewTurn {
  role: "companion" | "human";
  content?: string;
  verdict?: Record<string, unknown>;
  at?: string;
}

// Camel-cased client model matching the existing run-console ReviewGateMeta.
// The API normalizer translates the checkpoint's snake_case wire fields.
export interface PipelineBoardReviewGate {
  turns: PipelineBoardReviewTurn[];
  posture: string;
  mergeStrategy: string;
  mergeInto: string;
  maxTurns: number;
  reviewUrl?: string;
  verdict?: Record<string, unknown>;
}

// One dispatcher attempt associated with a native task-backed root.
export interface PipelineBoardAttempt {
  run_id?: string;
  status?: string;
  at?: string;
}

// Resolved hard dependency on another ticket (server-side enrichment).
export interface PipelineBoardBlocker {
  id: string;
  title?: string;
  state?: string;
  bot?: string;
  labels?: string[];
  satisfied: boolean;
  missing_labels?: string[];
}

// Reverse-index entry: a ticket that lists this card as a blocker.
export interface PipelineBoardBlocking {
  id: string;
  title?: string;
}

/** Spawned child ticket under a planner parent. */
export interface PipelineBoardChildRef {
  issue_id: string;
  title?: string;
  state?: string;
  bot_id?: string;
  card_id?: string;
}

/** Aggregated child statuses for a plan group face. */
export interface PipelineBoardChildrenSummary {
  total: number;
  ready: number;
  in_progress: number;
  done: number;
  failed: number;
  open: number;
}

// PipelineBoardCard is the read model the studio polls: one per root pipeline
// (or per not-yet-launched native task). Descendants are folded into their
// root — there are no per-child cards.
export interface PipelineBoardCard {
  id: string;
  kind: "task" | "run" | string;
  column_id: string;
  title: string;
  body?: string;

  // Native task provenance (present when the root is backed by a board issue).
  issue_id?: string;
  issue_state?: string;
  labels?: string[];
  priority?: number;

  // Hard-dependency graph (ticket roots). open_blocker_count > 0 means the
  // launch loop will refuse even if ready is true.
  blockers?: PipelineBoardBlocker[];
  open_blocker_count?: number;
  launch_blocked_reason?: string;
  blocking?: PipelineBoardBlocking[];

  // Planner provenance (distinct from hard blockers).
  parent_issue_id?: string;
  parent_title?: string;
  children?: PipelineBoardChildRef[];
  children_summary?: PipelineBoardChildrenSummary;
  /** planner | producer when known. */
  role?: string;

  // Run identity (empty for a not-yet-launched task card).
  run_id?: string;
  workflow_name?: string;
  bot_id?: string;
  status?: string;
  error?: string;

  // Failed lane — the ticket's last run failed/cancelled (Retry stages it
  // back to Ready), as opposed to a not-yet-ready Backlog ticket.
  failed?: boolean;
  // Ready lane (wire ID "opened") — a task-backed ticket staged (waiting for a
  // concurrency slot; the studio auto-launches it when one frees).
  ready?: boolean;

  // Ready lane — launch vars / task bot-args, and the concurrency-queue place.
  entry_input?: Record<string, unknown>;
  queue_position?: number;

  // IN_PROGRESS lane — node progress for the root and the whole tree.
  executed_nodes: number;
  total_nodes: number;
  tree_executed_nodes: number;
  tree_total_nodes: number;
  descendant_count?: number;
  // The whole run tree (root first, then descendants). The sidebar fans out
  // over these to aggregate every sub-bot's produced elements onto the card.
  tree_run_ids?: string[];
  pending_reviews?: PipelineBoardPendingReview[];

  // DONE lane — the pipeline's output (final_answer, else latest artifact).
  output?: string;

  attempts?: PipelineBoardAttempt[];
  created_at: string;
  updated_at: string;
}

// The local pipeline-concurrency gate. When `enabled` is false the other
// fields are zero and the Ready lane only holds not-yet-launched native tasks.
export interface PipelineConcurrency {
  enabled: boolean;
  max: number;
  active: number;
  waiting: number;
}

// PipelineBoard is the aggregate global read model returned by the board GET.
export interface PipelineBoard {
  columns: PipelineBoardColumn[];
  cards: PipelineBoardCard[];
  concurrency: PipelineConcurrency;
  generated_at?: string;
  topology_error?: string;
}

export interface CreatePipelineTaskInput {
  // The bot the created task runs as. Required — the board is global, so the
  // bot comes from the request body (not a URL path).
  bot: string;
  title: string;
  body?: string;
  labels?: string[];
  priority?: number;
  bot_args?: Record<string, string>;
  /** Hard deps: issue IDs that must reach done before this ticket can launch. */
  blockers?: string[];
  start?: boolean;
  /** Reconcile by (bot, bot_args.input_path) instead of creating a duplicate. */
  upsert?: boolean;
}

type UnknownRecord = Record<string, unknown>;

function record(value: unknown): UnknownRecord | null {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as UnknownRecord)
    : null;
}

function text(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

function numberValue(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function intValue(value: unknown, fallback = 0): number {
  const n = numberValue(value);
  return n === undefined ? fallback : Math.trunc(n);
}

function booleanValue(value: unknown): boolean {
  return value === true;
}

function stringArray(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value.filter((entry): entry is string => typeof entry === "string");
}

function normalizeAttempts(value: unknown): PipelineBoardAttempt[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value.map((entry) => {
    const source = record(entry) ?? {};
    return {
      ...(text(source.run_id) ? { run_id: text(source.run_id) } : {}),
      ...(text(source.status) ? { status: text(source.status) } : {}),
      ...(text(source.at) ? { at: text(source.at) } : {}),
    };
  });
}

function normalizeBlockers(value: unknown): PipelineBoardBlocker[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value
    .map((entry) => {
      const source = record(entry) ?? {};
      const id = text(source.id);
      if (!id) return null;
      return {
        id,
        ...(text(source.title) ? { title: text(source.title) } : {}),
        ...(text(source.state) ? { state: text(source.state) } : {}),
        ...(text(source.bot) ? { bot: text(source.bot) } : {}),
        ...(stringArray(source.labels) !== undefined
          ? { labels: stringArray(source.labels) }
          : {}),
        satisfied: booleanValue(source.satisfied),
        ...(stringArray(source.missing_labels) !== undefined
          ? { missing_labels: stringArray(source.missing_labels) }
          : {}),
      };
    })
    .filter((b): b is PipelineBoardBlocker => b !== null);
}

function normalizeBlocking(value: unknown): PipelineBoardBlocking[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value
    .map((entry) => {
      const source = record(entry) ?? {};
      const id = text(source.id);
      if (!id) return null;
      return {
        id,
        ...(text(source.title) ? { title: text(source.title) } : {}),
      };
    })
    .filter((b): b is PipelineBoardBlocking => b !== null);
}

function normalizeChildRefs(
  value: unknown,
): PipelineBoardChildRef[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value
    .map((entry) => {
      const source = record(entry) ?? {};
      const issueID = text(source.issue_id);
      if (!issueID) return null;
      return {
        issue_id: issueID,
        ...(text(source.title) ? { title: text(source.title) } : {}),
        ...(text(source.state) ? { state: text(source.state) } : {}),
        ...(text(source.bot_id) ? { bot_id: text(source.bot_id) } : {}),
        ...(text(source.card_id) ? { card_id: text(source.card_id) } : {}),
      };
    })
    .filter((c): c is PipelineBoardChildRef => c !== null);
}

function normalizeChildrenSummary(
  value: unknown,
): PipelineBoardChildrenSummary | undefined {
  const source = record(value);
  if (!source) return undefined;
  return {
    total: intValue(source.total, 0),
    ready: intValue(source.ready, 0),
    in_progress: intValue(source.in_progress, 0),
    done: intValue(source.done, 0),
    failed: intValue(source.failed, 0),
    open: intValue(source.open, 0),
  };
}

function normalizePendingReviews(
  value: unknown,
): PipelineBoardPendingReview[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value.map((entry) => {
    const source = record(entry) ?? {};
    const questions = record(source.questions) ?? undefined;
    const reviewBrief = normalizeReviewBrief(source.review_brief);
    const media = normalizeReviewMedia(source.media);
    const review = normalizeReviewGate(source.review);
    return {
      run_id: text(source.run_id) ?? "",
      ...(text(source.workflow_name)
        ? { workflow_name: text(source.workflow_name) }
        : {}),
      ...(text(source.bot_id) ? { bot_id: text(source.bot_id) } : {}),
      ...(text(source.node_id) ? { node_id: text(source.node_id) } : {}),
      ...(text(source.interaction_id)
        ? { interaction_id: text(source.interaction_id) }
        : {}),
      ...(questions ? { questions } : {}),
      updated_at: text(source.updated_at) ?? "",
      ...(text(source.instructions)
        ? { instructions: text(source.instructions) }
        : {}),
      ...(reviewBrief !== undefined ? { review_brief: reviewBrief } : {}),
      ...(media !== undefined ? { media } : {}),
      ...(review !== undefined ? { review } : {}),
      depth: Math.max(0, intValue(source.depth, 0)),
    };
  });
}

function normalizeReviewBrief(
  value: unknown,
): PipelineBoardReviewBrief | undefined {
  const source = record(value);
  if (
    !source ||
    source.version !== 1 ||
    source.source !== "ai" ||
    !Array.isArray(source.points) ||
    source.points.length < 1 ||
    source.points.length > 3
  ) {
    return undefined;
  }

  const points: string[] = [];
  for (const point of source.points) {
    if (typeof point !== "string" || !point.trim()) return undefined;
    points.push(point.trim());
  }

  return {
    version: 1,
    source: "ai",
    points: points as PipelineBoardReviewBriefPoints,
  };
}

function normalizeReviewGate(value: unknown): PipelineBoardReviewGate | undefined {
  const source = record(value);
  if (!source) return undefined;
  const turns: PipelineBoardReviewTurn[] = [];
  if (Array.isArray(source.turns)) {
    for (const entry of source.turns) {
      const turn = record(entry);
      const role = turn ? text(turn.role) : undefined;
      if (!turn || (role !== "companion" && role !== "human")) continue;
      const verdict = record(turn.verdict) ?? undefined;
      turns.push({
        role,
        ...(text(turn.content) ? { content: text(turn.content) } : {}),
        ...(verdict ? { verdict } : {}),
        ...(text(turn.at) ? { at: text(turn.at) } : {}),
      });
    }
  }
  const verdict = record(source.verdict) ?? undefined;
  return {
    turns,
    posture: text(source.posture) ?? "human_required",
    mergeStrategy: text(source.merge_strategy) ?? "squash",
    mergeInto: text(source.merge_into) ?? "current",
    maxTurns: Math.max(0, intValue(source.max_turns, 0)),
    ...(text(source.review_url) ? { reviewUrl: text(source.review_url) } : {}),
    ...(verdict ? { verdict } : {}),
  };
}

function normalizeReviewMedia(
  value: unknown,
): PipelineBoardReviewMedia[] | undefined {
  if (!Array.isArray(value)) return undefined;
  const out: PipelineBoardReviewMedia[] = [];
  for (const entry of value) {
    const source = record(entry);
    const path = source ? text(source.path) : undefined;
    const kind = source ? text(source.kind) : undefined;
    if (
      !path ||
      (kind !== "image" &&
        kind !== "audio" &&
        kind !== "video" &&
        kind !== "doc" &&
        kind !== "data")
    ) {
      continue;
    }
    const size = numberValue(source?.size);
    out.push({
      path,
      kind,
      ...(text(source?.run_id) ? { run_id: text(source?.run_id) } : {}),
      ...(text(source?.mime) ? { mime: text(source?.mime) } : {}),
      ...(size !== undefined && size >= 0 ? { size } : {}),
      ...(text(source?.caption) ? { caption: text(source?.caption) } : {}),
    });
  }
  return out;
}

export function normalizePipelineBoardColumn(
  value: unknown,
  index = 0,
): PipelineBoardColumn {
  const source = record(value) ?? {};
  const id = text(source.id) ?? `column-${index + 1}`;
  return {
    id,
    title: text(source.title) ?? id,
    kind: text(source.kind) ?? id,
  };
}

export function normalizePipelineBoardCard(
  value: unknown,
  index = 0,
): PipelineBoardCard {
  const source = record(value) ?? {};
  const runID = text(source.run_id);
  const issueID = text(source.issue_id);
  const id = text(source.id) ?? runID ?? issueID ?? `card-${index + 1}`;
  const entryInput = record(source.entry_input) ?? undefined;
  const attempts = normalizeAttempts(source.attempts);
  const reviews = normalizePendingReviews(source.pending_reviews);
  return {
    id,
    kind: text(source.kind) ?? (runID ? "run" : "task"),
    column_id: text(source.column_id) ?? "opened",
    title: text(source.title) ?? id,
    ...(text(source.body) ? { body: text(source.body) } : {}),
    ...(issueID ? { issue_id: issueID } : {}),
    ...(text(source.issue_state) ? { issue_state: text(source.issue_state) } : {}),
    ...(stringArray(source.labels) !== undefined
      ? { labels: stringArray(source.labels) }
      : {}),
    ...(numberValue(source.priority) !== undefined
      ? { priority: numberValue(source.priority) }
      : {}),
    ...(normalizeBlockers(source.blockers) !== undefined
      ? { blockers: normalizeBlockers(source.blockers) }
      : {}),
    ...(numberValue(source.open_blocker_count) !== undefined
      ? { open_blocker_count: intValue(source.open_blocker_count, 0) }
      : {}),
    ...(text(source.launch_blocked_reason)
      ? { launch_blocked_reason: text(source.launch_blocked_reason) }
      : {}),
    ...(normalizeBlocking(source.blocking) !== undefined
      ? { blocking: normalizeBlocking(source.blocking) }
      : {}),
    // Planner provenance. This normalizer is a WHITELIST — a field absent
    // here never reaches the views, however faithfully the server emits it
    // (that is exactly how the parent card lost its "N / M closed" children
    // counter and its Plan badge while /api/v1/pipeline-board was serving
    // both). Keep it in sync with PipelineBoardCard.
    ...(text(source.parent_issue_id)
      ? { parent_issue_id: text(source.parent_issue_id) }
      : {}),
    ...(text(source.parent_title)
      ? { parent_title: text(source.parent_title) }
      : {}),
    ...(normalizeChildRefs(source.children) !== undefined
      ? { children: normalizeChildRefs(source.children) }
      : {}),
    ...(normalizeChildrenSummary(source.children_summary) !== undefined
      ? { children_summary: normalizeChildrenSummary(source.children_summary) }
      : {}),
    ...(text(source.role) ? { role: text(source.role) } : {}),
    ...(runID ? { run_id: runID } : {}),
    ...(text(source.workflow_name)
      ? { workflow_name: text(source.workflow_name) }
      : {}),
    ...(text(source.bot_id) ? { bot_id: text(source.bot_id) } : {}),
    ...(text(source.status) ? { status: text(source.status) } : {}),
    ...(text(source.error) ? { error: text(source.error) } : {}),
    ...(typeof source.failed === "boolean" ? { failed: source.failed } : {}),
    ...(typeof source.ready === "boolean" ? { ready: source.ready } : {}),
    ...(entryInput ? { entry_input: entryInput } : {}),
    ...(numberValue(source.queue_position) !== undefined
      ? { queue_position: numberValue(source.queue_position) }
      : {}),
    executed_nodes: intValue(source.executed_nodes, 0),
    total_nodes: intValue(source.total_nodes, 0),
    tree_executed_nodes: intValue(source.tree_executed_nodes, 0),
    tree_total_nodes: intValue(source.tree_total_nodes, 0),
    ...(numberValue(source.descendant_count) !== undefined
      ? { descendant_count: numberValue(source.descendant_count) }
      : {}),
    ...(stringArray(source.tree_run_ids) !== undefined
      ? { tree_run_ids: stringArray(source.tree_run_ids) }
      : {}),
    ...(reviews !== undefined ? { pending_reviews: reviews } : {}),
    ...(text(source.output) ? { output: text(source.output) } : {}),
    ...(attempts !== undefined ? { attempts } : {}),
    created_at: text(source.created_at) ?? "",
    updated_at: text(source.updated_at) ?? "",
  };
}

function normalizeConcurrency(value: unknown): PipelineConcurrency {
  const source = record(value) ?? {};
  return {
    enabled: booleanValue(source.enabled),
    max: intValue(source.max, 0),
    active: intValue(source.active, 0),
    waiting: intValue(source.waiting, 0),
  };
}

// Keep all wire-shape tolerance in this module. Views always receive one
// canonical board with the four fixed columns and folded root cards.
export function normalizePipelineBoard(value: unknown): PipelineBoard {
  const root = record(value) ?? {};
  const columns = Array.isArray(root.columns) ? root.columns : [];
  const cards = Array.isArray(root.cards) ? root.cards : [];
  return {
    columns: columns.map(normalizePipelineBoardColumn),
    cards: cards.map(normalizePipelineBoardCard),
    concurrency: normalizeConcurrency(root.concurrency),
    ...(text(root.generated_at) ? { generated_at: text(root.generated_at) } : {}),
    ...(text(root.topology_error)
      ? { topology_error: text(root.topology_error) }
      : {}),
  };
}

export async function getPipelineBoard(opts?: {
  signal?: AbortSignal;
}): Promise<PipelineBoard> {
  const raw = await apiRequest<unknown>(BASE, { signal: opts?.signal });
  return normalizePipelineBoard(raw);
}

export async function createPipelineTask(
  input: CreatePipelineTaskInput,
): Promise<NativeIssue> {
  return apiRequest<NativeIssue>(`${BASE}/tasks`, {
    method: "POST",
    body: JSON.stringify(input),
  });
}

export interface BulkReadyInput {
  ids?: string[];
  family_id?: string;
  pipeline_kind?: string;
  only_satisfied?: boolean;
}

export interface BulkReadyResult {
  ready: string[];
  waiting_deps?: string[];
  skipped?: string[];
  skipped_why?: Record<string, string>;
}

/** Stage many tickets Ready (or waiting_deps). Used by multi-select bulk. */
export async function bulkReadyPipelineTasks(
  input: BulkReadyInput,
): Promise<BulkReadyResult> {
  return apiRequest<BulkReadyResult>(`${BASE}/bulk/ready`, {
    method: "POST",
    body: JSON.stringify(input),
  });
}

export interface BulkDeleteInput {
  ids: string[];
}

export interface BulkDeleteResult {
  deleted: string[];
  skipped?: string[];
  skipped_why?: Record<string, string>;
}

/** Delete many tickets (issue only). Skips tickets with active runs. */
export async function bulkDeletePipelineTasks(
  input: BulkDeleteInput,
): Promise<BulkDeleteResult> {
  return apiRequest<BulkDeleteResult>(`${BASE}/bulk/delete`, {
    method: "POST",
    body: JSON.stringify(input),
  });
}

// markPipelineTaskReady flips a task-backed ticket between the ready and
// draft states (both stay in the Todo lane) — the write behind the board's
// Mark ready / Unmark ready / Retry buttons. The studio auto-launches ready
// tickets when a concurrency slot frees.
export async function markPipelineTaskReady(
  taskId: string,
  ready: boolean,
): Promise<void> {
  await apiRequest<unknown>(
    `${BASE}/tasks/${encodeURIComponent(taskId)}/ready`,
    {
      method: "POST",
      body: JSON.stringify({ ready }),
    },
  );
}

// deletePipelineTask removes a ticket — the Backlog card's Delete button.
// Server-guarded: refused (409) while any run in the ticket's tree is still
// active, so a live pipeline can never be detached from its ticket. Runs are
// never deleted, only the native issue.
export async function deletePipelineTask(taskId: string): Promise<void> {
  await apiRequest<unknown>(`${BASE}/tasks/${encodeURIComponent(taskId)}`, {
    method: "DELETE",
  });
}

// resetPipelineTask restarts an in-progress ticket from zero: the server
// cancels every still-active run in the ticket's tree, then restages the
// ticket to Ready so the admission loop relaunches it fresh. Refused (409)
// when a run is held by another process.
export async function resetPipelineTask(taskId: string): Promise<void> {
  await apiRequest<unknown>(
    `${BASE}/tasks/${encodeURIComponent(taskId)}/reset`,
    { method: "POST", body: JSON.stringify({}) },
  );
}

// launchPipelineTask starts a ticket immediately, jumping the admission
// loop's priority order (the Opened → In progress drag). The server still
// refuses (409) on an active run, an unfinished hard dependency, or a full
// concurrency cap — those are correctness, not ranking.
export async function launchPipelineTask(taskId: string): Promise<void> {
  await apiRequest<unknown>(
    `${BASE}/tasks/${encodeURIComponent(taskId)}/launch`,
    { method: "POST", body: JSON.stringify({}) },
  );
}

// PipelineTaskPatch is the editable surface of a not-yet-run (Backlog/ready)
// ticket. All fields optional — only sent fields are applied server-side.
export interface PipelineTaskPatch {
  title?: string;
  body?: string;
  labels?: string[];
  priority?: number;
  bot?: string;
  bot_args?: Record<string, string>;
  /** Replace hard-dep list wholesale; empty array clears. */
  blockers?: string[];
}

// updatePipelineTask edits a Backlog (or ready-but-unlaunched) ticket before it
// runs — title, input (bot_args), bot, description, labels, priority.
export async function updatePipelineTask(
  taskId: string,
  patch: PipelineTaskPatch,
): Promise<void> {
  await apiRequest<unknown>(`${BASE}/tasks/${encodeURIComponent(taskId)}`, {
    method: "PATCH",
    body: JSON.stringify(patch),
  });
}

// pipelineBoardImageURL builds the URL serving one workdir-relative image for
// the card sidebar's input thumbnails (e.g. a ticket's character-reference
// list). Segment-encode so subdirectories survive — encodeURIComponent on the
// whole path would clobber the "/" separators.
export function pipelineBoardImageURL(relPath: string): string {
  const segments = relPath.split("/").map(encodeURIComponent).join("/");
  return `${BASE}/workspace-images/${segments}`;
}
