package e2e

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	iterlog "github.com/SocialGouv/iterion/pkg/log"
	"github.com/SocialGouv/iterion/pkg/runtime"
	"github.com/SocialGouv/iterion/pkg/runview"
	"github.com/SocialGouv/iterion/pkg/store"
	"github.com/SocialGouv/iterion/pkg/workspacetrack"
)

// TestRewindRestoresWorkspaceEndToEnd is the contract test the engine and
// the rewind never had between them.
//
// The engine WRITES boundary labels and the rewind READS them from
// another package. While the format was duplicated, appending a suffix on
// the producing side left every unit suite green — the drift showed up
// only as a "no snapshot recorded" skip, which reads like a missing
// feature rather than a bug. This exercises the real path: a real engine
// with a real tracker writes the labels, and Service.Rewind resolves one.
//
// It also covers the case unit tests cannot: a node whose product is
// FILES rather than its output map, on a run with no git worktree.
func TestRewindRestoresWorkspaceEndToEnd(t *testing.T) {
	wf := compileFixtureStubSafe(t, "rewind_mini.bot")

	dir := t.TempDir()
	storeDir := filepath.Join(dir, "store")
	ws := filepath.Join(dir, "workspace")
	if err := os.MkdirAll(ws, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	writeWS(t, ws, "docs/intro.md", "intro v1\n")

	st, err := store.New(storeDir)
	if err != nil {
		t.Fatalf("store: %v", err)
	}
	tracker := workspacetrack.NewNative(storeDir)

	// `implement` writes a doc set and returns only a summary — the shape
	// the whole feature exists for.
	exec := newScenarioExecutor()
	exec.on("implement", func(_ map[string]any) (map[string]any, error) {
		writeWS(t, ws, "docs/intro.md", "intro v2 REWRITTEN\n")
		writeWS(t, ws, "docs/api.md", "generated by implement\n")
		return map[string]any{"value": "wrote the docs"}, nil
	})
	exec.on("verify", func(_ map[string]any) (map[string]any, error) {
		return nil, errors.New("verify blew up")
	})

	const runID = "e2e-rewind-workspace"
	eng := runtime.New(wf, st, exec,
		runtime.WithLogger(iterlog.Nop()),
		runtime.WithWorkDir(ws),
		runtime.WithWorkspaceTracker(tracker),
	)
	if err := eng.Run(context.Background(), runID, nil); err == nil {
		t.Fatal("expected the run to fail at verify")
	}

	// The engine must have recorded a pre-execution boundary for the node
	// we are about to rewind to — through the SHARED label builder.
	preLabel := workspacetrack.Label(workspacetrack.PhasePre, "implement", 0)
	if _, ok := tracker.Resolve(runID, preLabel); !ok {
		t.Fatalf("no %q boundary recorded — the engine and the rewind disagree on the label", preLabel)
	}

	svc, err := runview.NewService(storeDir, runview.WithLogger(iterlog.Nop()))
	if err != nil {
		t.Fatalf("NewService: %v", err)
	}
	result, err := svc.Rewind(context.Background(), runview.RewindSpec{
		RunID:      runID,
		NodeID:     "implement",
		SourcePath: filepath.Join("testdata", "rewind_mini.bot"),
	})
	if err != nil {
		t.Fatalf("Rewind: %v", err)
	}
	if result.Files == nil || !result.Files.Reverted {
		t.Fatalf("Files = %+v, want the workspace restored (skip reason: %v)", result.Files, result.Files)
	}

	if got := readWS(t, ws, "docs/intro.md"); got != "intro v1\n" {
		t.Errorf("docs/intro.md = %q, want the state implement started from", got)
	}
	if _, err := os.Stat(filepath.Join(ws, "docs/api.md")); !os.IsNotExist(err) {
		t.Error("the file implement created survived the rewind")
	}
}

func writeWS(t *testing.T, dir, name, body string) {
	t.Helper()
	p := filepath.Join(dir, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

func readWS(t *testing.T, dir, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(name)))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	return string(b)
}
