#!/usr/bin/env bash
# Land a tap update through the merge queue instead of pushing to main.
#
# Usage:
#   scripts/brew-tap-pr.sh branch  <tag>   # switch to this tag's tap branch
#   scripts/brew-tap-pr.sh publish <tag>   # commit + push + PR + auto-merge
#
# A direct push to `main` invalidates the merge group at the head of the
# queue and makes it rebuild — about 20 to 25 minutes, paid by whichever PR
# is first in line, once per release on top of the release commit's own
# replay. So the tap change takes an ordered slot of its own: one branch per
# tag, one PR, auto-merge armed.
#
# Called once per release pipeline (release.yml and desktop-release.yml each
# fire the workflow), so both subcommands are idempotent: the second call
# re-uses the first call's branch and PR, adding the desktop cask hash to
# the same slot.
#
# `branch` expects a git repo on `main` with `origin` fetchable; `publish`
# expects the tap files already rewritten by scripts/update-brew-tap.sh, a
# git identity, push credentials on `origin`, and `gh` authenticated as an
# identity that may open a PR (GH_TOKEN).
set -euo pipefail

cmd="${1:?usage: brew-tap-pr.sh <branch|publish> <tag>}"
tag="${2:?usage: brew-tap-pr.sh <branch|publish> <tag>}"
branch="chore/brew-tap-${tag}"

case "$cmd" in
branch)
  # Build on this tag's own branch when it already exists (the first
  # pipeline opened it), so the second pass adds to that slot instead of
  # dropping the first pass's formula.
  if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
    git fetch origin "$branch"
    git checkout -B "$branch" "origin/$branch"
  else
    git checkout -B "$branch"
  fi
  echo "on ${branch}"
  ;;

publish)
  git add Formula/iterion.rb Cask/iterion-desktop.rb
  if git diff --staged --quiet; then
    # Not an error: the second pipeline's pass sees artefacts the first
    # already wrote, and a re-run of the same pass sees its own commit.
    echo "tap already up to date for ${tag}, nothing to commit"
  else
    git commit -m "chore(brew): update tap to ${tag}"
    git push origin "$branch"
  fi

  # No `[skip ci]` anywhere in that message on purpose: the required checks
  # must run on this PR, or auto-merge waits on contexts that never report.

  # One open PR per tag. `--head` matches the branch, so a merged PR whose
  # branch was recreated does not count.
  existing="$(gh pr list --state open --head "$branch" --json number --jq '.[0].number // empty')"
  if [ -n "$existing" ]; then
    echo "PR #${existing} already open for ${branch}; the push above updated it"
  elif ! git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
    # Nothing pushed for this tag and no open PR: the tap was already current.
    # Not an exit — the supersede sweep below still has to run, or a stale
    # older slot sits there with auto-merge armed, waiting to publish a
    # downgrade the moment its checks go green.
    echo "nothing pushed for ${tag} and no open PR — the tap was already current"
  else
    gh pr create \
      --base main \
      --head "$branch" \
      --title "chore(brew): update tap to ${tag}" \
      --body "Homebrew formula + cask for \`${tag}\`, generated by \`scripts/update-brew-tap.sh\`.

Landing through the merge queue rather than as a direct push to \`main\`: a
direct push invalidates the group at the head of the queue and makes every
PR behind it rebuild."

    # Auto-merge is what puts it in the queue. A failure here is loud on
    # purpose: a tap PR nobody merges is a stale formula plus an open PR the
    # next release has to close.
    gh pr merge "$branch" --auto --squash
  fi

  # A tap PR for an EARLIER tag is superseded, not to be merged: its formula
  # would downgrade the published version. Close it and drop its branch.
  #
  # "Earlier" is a VERSION comparison, not "any branch that is not mine".
  # `workflow_dispatch` backfills an arbitrary old tag on purpose (`inputs.tag`
  # in brew-update.yml), so a v0.5.0 backfill run reaches this loop with
  # branch=chore/brew-tap-v0.5.0 while the current release's PR is open — and
  # a name-inequality test would close and `--delete-branch` the NEWER slot,
  # keeping the release iterion actually shipped out of the tap.
  #
  # --limit: the sweep filters client-side, and `gh pr list` returns 30 by
  # default, newest-first. The entries that fall off that page are precisely
  # the older ones this loop exists to close.
  #
  # Anything whose suffix is not a v-prefixed version is left alone: the only
  # safe direction for a name this script cannot order is "not mine to close".
  gh pr list --state open --limit 200 --json number,headRefName \
    --jq ".[] | select(.headRefName | startswith(\"chore/brew-tap-\")) | select(.headRefName != \"${branch}\") | [.number, .headRefName] | @tsv" |
    while read -r other otherRef; do
      [ -n "$other" ] || continue
      otherTag="${otherRef#chore/brew-tap-}"
      case "$otherTag" in
      v[0-9]*) ;;
      *)
        echo "leaving tap PR #${other} (${otherRef}): suffix is not a version this script can order"
        continue
        ;;
      esac
      # STRICTLY older, by version sort: `sort -V` orders v3.112.9 before
      # v3.112.25, which a lexical compare does not. The equality arm is
      # redundant with the jq filter above and kept anyway — it is what makes
      # "not strictly older" the default for any pair `sort -V` ranks equal.
      if [ "$otherTag" = "$tag" ] ||
        [ "$(printf '%s\n%s\n' "$otherTag" "$tag" | sort -V | head -n1)" != "$otherTag" ]; then
        echo "leaving tap PR #${other} (${otherTag}): not older than ${tag}"
        continue
      fi
      echo "closing superseded tap PR #${other} (${otherTag} < ${tag})"
      gh pr close "$other" --delete-branch \
        --comment "Superseded by the tap update for \`${tag}\`."
    done
  ;;

*)
  echo "unknown subcommand: ${cmd}" >&2
  exit 2
  ;;
esac
